# version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # web:
  #     build: .
  #     restart: always
  #     depends_on:
  #       - db
  #     env_file:
  #       - .env
  #     volumes:
  #       - .:/app
  #     ports:
  #       - "8000:8000"



volumes:
  pgdata: